apiVersion: apps/v1
kind: Deployment
metadata:
  name: your-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mynodeapp
  template:
    metadata:
      labels:
        app: mynodeapp
    spec:
      containers:
        - name: my-kubernetes-container
          image: zinx666/myfirstdockerrepo:latest
          ports:
            - containerPort: 8080
