name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your main branch name (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build  # Replace 'build' with the actual build script/command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./views/pages  # Replace with the path to your build output

